<?php
/**
 * IDEALIAGroup srl
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.idealiagroup.com/magento-ext-license.html
 *
 * @category   IG
 * @package    IG_FloatingMenu
 * @copyright  Copyright (c) 2011-2012 IDEALIAGroup srl (http://www.idealiagroup.com)
 * @license    http://www.idealiagroup.com/magento-ext-license.html
 */
?>
<div id="ig-floatingmenu-container" class="header">
	<div class="ig-floatingmenu-wrapper">
		<div id="ig-floatingmenu-quick" style="display: none"></div> 
		
		<div class="coisas-menu">
			<img src="<?php echo $this->getSkinUrl() ?>images/mascote_jipinho_float.png" title="Mascote Jipinho" class="logo-fixed" />
			<a href="#" class="atendimento"><img src="<?php echo $this->getSkinUrl() ?>images/atendimento_online_float.png" title="Moveis Jipinho" /></a>
			<div id="ig-floatingmenu-search"></div>
			<div class="div-carrinho">
				<div class="itens-cart">
                                    <?php if(Mage::getModel('checkout/cart')->getQuote()->getItemsCount()):?>
                                        <?php echo Mage::getModel('checkout/cart')->getQuote()->getItemsCount() ?> Itens 
                                    <?php else:?>
                                        0 Itens 
                                    <?php endif;?>
                                </div> 
				<?php //echo $this->getChildHtml('cart_sidebar') ?>
			</div>
		</div>
		<div id="ig-floatingmenu-search"></div>
		
		
		<div style="clear:both"></div>
		<div id="ig-floatingmenu-nav" style="display: none"></div>
		
		
	</div>
</div>
<script type="text/javascript">igFloatingMenuStart()</script>
